# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-12 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20190712_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
